<?php $title = "Accueil"; ?>

<?php ob_start() ?>

<button><a href="?route=index">Tous les films</a></button>

<?php foreach ($genres as $genre) { ?>
  <button><a href="?route=index&genre=<?= $genre->getId() ?>">
    <?= htmlspecialchars($genre->getName()) ?>
  </a></button>
<?php } ?>

  <button><a href="?route=index">n/c</a></button>
  <button><a href="?route=index&filter=watched">👁️</a></button>
  <button><a href="?route=index&filter=towatch">🕒</a></button>

  <div class="films-grid">
  <?php foreach ($films as $film) { ?>
    <div class="card">
      <?php if ($film->getPoster_path()) { ?>
        <img src="https://image.tmdb.org/t/p/w500<?= $film->getPoster_path() ?>" alt="<?= htmlspecialchars($film->getTitle()) ?>">
      <?php } else { ?>
        <div class="no-poster">🎥</div>
      <?php } ?>
      <p class="card-title"><?= htmlspecialchars($film->getTitle()) ?></p>
      <p class="card-meta">📅 <?= $film->getRelease_date() ?> <?= $film->getIsWatched() ? '👁️' : '🕒' ?></p>
    </div>
  <?php } ?>
</div>

<?php $content = ob_get_clean() ?>
<?php require __DIR__ . '/../base.phtml' ?>