<nav>
        <input type="checkbox" id="nav-toggle">
        <label class="hamburger" for="nav-toggle">☰</label>
        <ul id="nav-menu">
            <li><a href="?route=index">📼 <span class="label">VIDÉOTHEQUE</span></a></li>
            <li><a href="?route=search">🔍 <span class="label">RECHERCHE</span></a></li>
            <li><a href="?route=genres">🎭 <span class="label">CATÉGORIES</span></a></li>
        </ul>
</nav>