<?php $title = "Ajouter une catégorie"; ?>

<?php ob_start() ?>

<div class="genres-container">
    <form method="POST" action="?route=genreCreate">

        <?= \Cine\App\Security\CsrfToken::field() ?>
        
        <div class="genres-header">
            <h2>Ajouter une catégorie</h2>

            <input 
                type="text" 
                name="name" 
                class="search-input" 
                placeholder="Nom de la catégorie" 
                required
            >
        </div>

        <div class="btn-back-container">
            <button type="submit" class="btn-submit">💾 Enregistrer</button>
            <a href="?route=genres" class="btn-back"> Annuler</a>
        </div>
    </form>
</div>

<?php $content = ob_get_clean() ?>
<?php require __DIR__ . '/../base.phtml' ?>