<?php $title = "Modifier une catégorie"; ?>

<?php ob_start() ?>

<div class="genres-container">
    <form method="POST" action="?route=genreUpdate&id=<?= $genre->getId() ?>">

        <?= \Cine\App\Security\CsrfToken::field() ?>
        
        <div class="genres-header">
            <h2>✏️ Modifier une catégorie</h2>
            <input type="text" name="name" class="search-input" 
                value="<?= htmlspecialchars($genre->getName()) ?>" required>
        </div>

        <div class="btn-back-container">
            <button type="submit" class="btn-submit">💾 Enregistrer</button>
            <a href="?route=genres" class="btn-back">Annuler</a>
        </div>

    </form>
</div>

<?php $content = ob_get_clean() ?>
<?php require __DIR__ . '/../base.phtml' ?>