<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
</head>
<body>
    <!-- Header -->
    <h1>🎬 CinéStream +</h1>
    <p>Votre cinéma, partout, à tout moment. </p>
    <!-- Menu -->
    <ul>
        <li>
            <a href="">📼 VIDÉOTHEQUE</a>
            <a href="">🔍 RECHERCHE</a>
        </li>
    </ul>
    <?= $content ?>

</body>
</html>
