<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <title><?= $title ?></title>
</head>
<body>
    
    <?php require __DIR__ . '/_shared/_header.phtml' ?>
    <?php require __DIR__ . '/_shared/_nav.phtml' ?>

        <?php if (isset($_SESSION['flash'])) { ?>
        <div class="flash-message"><?= $_SESSION['flash'] ?></div>
        <?php unset($_SESSION['flash']); ?>
    <?php } ?>
    
    <main>
        <?= $content ?>
    </main>

</body>
</html>